localhost:
  name: iMES
  banner:
    title: imes.net
    loading: true
productions:
  - Id: 1
    Title: PC
    Desc: PC
  - Id: 2
    Title: 机顶盒
    Desc: IPTV Box
  - Id: 3
    Title: 手机
    Desc: Mobile
languages:
  - Ruby
  - Perl
  - Python
websites:
  YAML: yaml.org
  Ruby: ruby-lang.org
  Python: python.org
  Perl: use.perl.org
